jobs:
  main:
    image: golang
    steps:
      - dir: pwd && ls && env
      - get: go get -t ./...
      - vet: go vet ./...
      - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
      - test: go test ./...
      - build: go build -a -o log-service
    environment:
      GOPATH: /sd/workspace
